id: amp-application-panel

info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Application Management Panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: amp
    shodan-query: title:"AMP - Application Management Panel"
    vendor: cubecoders
    verified: true
  tags: panel,amp,cubecoders

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>AMP - Application Management Panel</title>"

      - type: word
        part: header
        words:
          - "text/html"
# digest: 490a00463044022001f279a936bf2746faf11df9f5e6c7ec5dfcb230319b17e97649696af44561f602203d4cd614cdc13e7c5718cc1e8c9fad14b631666ee55b676a4c32c4365b3ed320:922c64590222798bb761d5b6d8e72950