id: basic-cors-misconfig

info:
  name: Basic CORS misconfiguration
  author: nadino (modified by jtcsec)
  severity: medium
  tags: cors

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    headers:
      Origin: https://evil.com

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Access-Control-Allow-Origin: https://evil.com"
          - "Access-Control-Allow-Credentials: true"
        condition: and
        part: header
    extractors:
      - type: regex
        name: firstchunk
        part: header
        regex:
                - Access\-Control\-Allow\-Origin\:[\s]+([^\s]+)

