id: bitbucket-pipelines

info:
  name: BitBucket Pipelines Configuration Exposure
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"bitbucket-pipelines.yml"
  tags: exposure,bitbucket,devops,cicd,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/bitbucket-pipelines.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'pipelines:'
          - 'step:'
        condition: and

      - type: status
        status:
          - 200

# digest: 490a00463044022007328c206da35551b76be9d31fef4244abbd54c4f29c466362271bcaa766791c02207ea142024f126767b6c73826034e5958f9fd4f83f9f330900ea5f3184b8b5a98:922c64590222798bb761d5b6d8e72950
