id: broadcom-backupsettings-exposure
info:
  name: Broadcom Backup Settings Exposure
  author: trainzment
  severity: high
  tags: router,exposed,backup

http:
  - method: GET
    path:
      - "{{BaseURL}}/backupsettings.conf"
    matchers:
      - type: word
        words:
          - "<X_BROADCOM_COM_LoginCfg>"
        part: body
    extractors:
      - type: regex
        part: body
        regex:
          - '<UserPassword>([^<]+)</UserPassword>'
