id: cache-control-header-misconfiguration

info:
  name: Cache-Control HTTP response header misconfiguration
  author: sklnhunt
  severity: medium
  description: The 'Cache-Control' HTTP response header with the 'private' directive indicates that a resource specific to the user can be cached on a client device.
  tags: misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}"
  
    matchers:
      - type: regex
        name: cache-control header
        regex:
          - "(?i)cache-control: private"
        part: header
