id: cors-misconfiguration
info:
  name: CORS Misconfiguration
  author: exxonabhijit
  severity: medium
  description: Identifies insecure CORS policies allowing arbitrary origins.

requests:
  - method: OPTIONS
    path:
      - "{{BaseURL}}"

    headers:
      Origin: "http://evil.com"
      Access-Control-Request-Method: "GET"

    matchers:
      - type: regex
        regex:
          - "Access-Control-Allow-Origin: \\*"
          - "Access-Control-Allow-Origin: http://evil.com"
