id: deployment-interface-exposed

info:
  name: Deployment Management Interface - Exposed
  author: DhiyaneshDK
  severity: medium
  description: |
   Deployment Management Interface is exposed. This exposure could potentially allow unauthorized access to the management interface
  metadata:
    verified: true
    max-request: 1
  tags: deployment,management,misconfig

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<title>Deployment Management Interface</title>"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100d358167bb7a0ef9ceb058f53d3781cea2f2b12a84590e2fef1fd199073a6de4e02205040b1ed5c89a64f94e43860963f62e49db70866e63e61d2b7dc319540b28ca6:922c64590222798bb761d5b6d8e72950