
id: drupal_module-l10n_update-insecure-server-configuration
info:
  name: drupal_module-l10n_update-insecure-server-configuration
  author: Bishopfox
  severity: medium
  description: "This module enables you to automatically download and update the sites interface translation by fetching them from localize.drupal.org or any other Localization server. The module doesnt sufficiently protect the directory it stores translation files in. Its conventional for directories which may be writeable to be protected by a .htaccess file to prevent malicious PHP files placed within them being executed by the webserver. This vulnerability is mitigated by the fact that an attacker typically wouldnt be able to place a malicious file in the modules storage directory."
  reference:
    - https://www.drupal.org/sa-contrib-2019-072
  metadata:
    security-risk: "Moderately critical 10∕25 AC:Complex/A:Admin/CI:Some/II:Some/E:Theoretical/TD:Uncommon"
    vulnerability: "insecure-server-configuration"
    fofa-query: "/sites/all/modules/l10n_update/"
    google-query: "inurl:'/sites/all/modules/l10n_update/"
    impact: medium
    type: indicator
    created_at: '0001-01-01T00:00:00Z'
  tags: drupal

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/sites/all/modules/l10n_update/l10n_update.info"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'l10n_update'
        part: body

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'

      - type: dsl
        dsl:
         - compare_versions(version, '7.x-2.2')
         - compare_versions(version, '7.x-2.1')
         - compare_versions(version, '7.x-2.0')
         - compare_versions(version, '7.x-1.1')
         - compare_versions(version, '7.x-1.0')
