
id: drupal_module-config_pages-information-disclosure
info:
  name: drupal_module-config_pages-information-disclosure
  author: me
  severity: medium
  description: "This module enables you to build administrative pages for managing configuration objects, which may then be used elsewhere in the site. The module doesnt sufficiently validate access when the JSONAPI module is also installed. This vulnerability is mitigated by the fact that it only affects sites when the JSONAPI module is installed."
  reference:
    - https://www.drupal.org/sa-contrib-2023-037
  metadata:
    security-risk: "Moderately critical 12 ∕ 25 AC:Basic/A:None/CI:Some/II:None/E:Theoretical/TD:Default"
    vulnerability: "information-disclosure"
    fofa-query: "/sites/all/modules/config_pages/"
    google-query: "inurl:'/sites/all/modules/config_pages/"
    impact: medium
    type: indicator
    created_at: '2025-01-09'
  tags: drupal

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/sites/all/modules/config_pages/config_pages.info"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'
        condition: and
        
      - type: status
        status:
          - 200
        condition: and
        
      - type: word
        words:
          - 'config_pages'
        part: body
        condition: and

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'

      - type: dsl
        dsl:
         - compare_versions(version, '<= 2.9.0')
