
id: drupal_module-config_perms-access-bypass
info:
  name: drupal_module-config_perms-access-bypass
  author: Bishopfox
  severity: medium
  description: "This module enables you to add and manage additional custom permissions through the administration UI. The module doesnt sufficiently check for the proper access permissions to this page. This vulnerability is mitigated by the fact that an attacker must know the route of the Custom Permissions administration form though this is easily known."
  reference:
    - https://www.drupal.org/sa-contrib-2019-055
  metadata:
    security-risk: "Critical 16∕25 AC:Basic/A:None/CI:Some/II:Some/E:Theoretical/TD:All"
    vulnerability: "access-bypass"
    fofa-query: "/sites/all/modules/config_perms/"
    google-query: "inurl:'/sites/all/modules/config_perms/"
    impact: medium
    type: indicator
    created_at: '0001-01-01T00:00:00Z'
  tags: drupal

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/sites/all/modules/config_perms/config_perms.info"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'config_perms'
        part: body

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - 'version = "([0-9]+\.x-[0-9]+\.[0-9]+)"'

      - type: dsl
        dsl:
         - compare_versions(version, '8.x-1.1')
         - compare_versions(version, '8.x-1.0')
