id: exposed-git-config

info:
  name: Exposed .git/config
  author: CyberCavalcante
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[core]"
        part: body


          
