id: insecure-appsettings-access

info:
  name: Insecure Access to AppSettings
  author: YoruYagami
  severity: medium
  description: Detects direct access to configuration settings via ConfigurationManager.AppSettings, which may expose sensitive data stored in plain text.
  remediation: Encrypt or secure sensitive configuration data and use secure vaults or protected configuration sections.
  reference:
    - https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.appsettings
  classification:
    cwe-id: CWE-311
  tags: csharp,file

file:
  - extensions:
      - all
    matchers:
      - type: regex
        regex: 'ConfigurationManager\.AppSettings'
