id: keycloak-openid-config

info:
  name: Keycloak OpenID Configuration - Detect
  author: rodnt
  severity: info
  description: Keycloak Openid configuration information was detected.
  reference:
    - https://issues.jboss.org/browse/KEYCLOAK-571
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: keycloak,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.well-known/openid-configuration"
      - "{{BaseURL}}/auth/realms/master/.well-known/openid-configuration"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'issuer'
          - 'authorization_endpoint'
          - 'token_endpoint'
          - 'userinfo_endpoint'
          - 'jwks_uri'
        condition: and

# digest: 4a0a0047304502202046a594d193d1917e5a438527f36b33ee7230c0f035de7c5019809cfa9b2113022100fd74ed3389f1df0bc3eb27dfb579eb6e2d0ed29f38bdb8e69c2de1bcb11523c9:922c64590222798bb761d5b6d8e72950
