id: local-settings-python
info:
  name: Detect Python Config Sensitive Information Exposure
  author: nored0x
  severity: high
  description: |
    Detects exposure of sensitive information (SECRETS, passwords, API keys, TOKENS) in a Python configuration file.
  tags:
    - sensitive-information
    - python-config

requests:
  - method: GET
    path:
      - '{{BaseURL}}/local_settings.py'
    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - 'USER'
          - 'PASSWORD'
          - 'HOST'
          - 'SSH'
          - 'SECRET'
          - 'KEY'
          - 'django'
          - 'TOKEN'



