id: log4net-config

info:
  name: C# log4net Configuration Check
  author: YoruYagami
  severity: low
  description: Detects references to log4net configuration (log4net.config, log4net.xml) which may expose logs or be misconfigured.
  remediation: Ensure logging does not store sensitive data; restrict access to log files.
  reference:
    - https://cwe.mitre.org/data/definitions/532.html
  classification:
    cwe-id: CWE-532
  tags: csharp,file

file:
  - extensions:
      - all
    matchers:
      - type: word
        words:
          - "log4net.config"
          - "log4net.xml"
