id: nuget-package-config

info:
  name: NuGet Package.config File Disclosure
  author: DhiyaneshDK
  severity: info
  reference:
    - https://learn.microsoft.com/en-us/nuget/reference/packages-config
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"packages.config"
  tags: exposure,sass,devops,cicd,nuget,files

http:
  - method: GET
    path:
      - '{{BaseURL}}/packages.config'
      - '{{BaseURL}}/.nuget/packages.config'

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<?xml version="1.0" encoding="utf-8"?>'
          - '<packages>'
          - '</packages>'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a0047304502202e84589746805c8bbca0cf94b1bffa171136ccc8b6ad5616fa29d2951f1284d3022100dbd8a24d22bbd58ed9e38a8775142f1982ed9b338529bac0a05e6872e95f2d65:922c64590222798bb761d5b6d8e72950
