id: openstack-config

info:
  name: Openstack - Infomation Disclosure
  author: MayankPandey01
  severity: low
  description: |
    Openstack exposing Configuration or settings related to the Swift object storage system.
  reference:
    - https://docs.openstack.org/python-cloudkittyclient/stein/api_reference/info.html
  metadata:
    max-request: 2
    shodan-query: http.favicon.hash:786533217
  tags: exposure,misconfig,openstack

http:
  - method: GET
    path:
      - "{{BaseURL}}/info"
      - "{{BaseURL}}/v1/info"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '{"formpost"'
          - '"bulk_'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200

# digest: 4b0a00483046022100c504ae86098c92cdf1075b41054fd034ae21ecebd6d3aba49a10adb53a4c2356022100915148716537ac9841a78f79df37fb16c699ac1852fec8448ebb9746215f4d40:922c64590222798bb761d5b6d8e72950
