id: oracle-application-server-panel

info:
  name: Oracle Application Server Panel - Detect
  author: righettod
  severity: info
  description: |
    Oracle Application Server login panel was detected.
  reference:
    - https://www.oracle.com/middleware/technologies/internet-application-server.html
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"Oracle Containers for J2EE"
  tags: panel,oracle,containers,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/em/console/ias/oc4j/home"
      - "{{BaseURL}}"

    stop-at-first-match: true
    host-redirects: true
    max-redirects: 2

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(to_lower(body), "login to oracle application server control", "oracle enterprise manager")'
        condition: and

    extractors:
      - type: regex
        group: 1
        regex:
          - '(?i)Copyright\s+&copy;\s+([0-9,\s]+),\s+Oracle'
# digest: 4a0a00473045022100b5e77797f9eae4009f93063d3efcfe86e925c29a78b7bea924eb20b33a306238022056292a2ea5cb1b94ea724d63ea9f73e8be4207bb5e00e45cc499c3f7cc98f401:922c64590222798bb761d5b6d8e72950