id: phinx-config

info:
  name: Phinx Configuration Exposure
  author: DhiyaneshDk
  severity: medium
  reference:
    - https://book.cakephp.org/phinx/0/en/configuration.html
    - https://github.com/cakephp/phinx
    - https://www.tenable.com/plugins/was/113433
    - https://phinx.org/
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"phinx.yml"
  tags: devops,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/phinx.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'paths:'
          - 'environments:'
          - 'development:'
        condition: and

      - type: status
        status:
          - 200

# digest: 490a00463044022013d72ca531849ffa27bee5457914cf1dfcee951495529d8d98bbbac22670391d022016f8615b830e6e549fe1dcb869367e344989c2d8741e37217bf8917d7514e32b:922c64590222798bb761d5b6d8e72950
