id: prometheus-webapi-via-grafana

info:
  name: Prometheus Config API Endpoint Discovery
  author: Esonhugh-self-maintained
  severity: medium
  description: A Prometheus API endpoint via grafana Public Access was discovered.
  reference:
    - https://hackerone.com/reports/764731
  tags: prometheus,misconfig,grafana

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/datasources/proxy/1/api/v1/query?query=114*514"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"status":'
          - '"success"'
          - '"data":'
          - '"resultType":'
          - '"scalar"'
          - "58596" # 114*514 result
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
# digest: 4b0a00483046022100eb4e191c8826d91cad5dd11dbf61793a859d7f613a525010a7c3e6074e26fbc0022100d9768b52c1515f8cb50e9a6821d77fad6274fe81c77fab5d29cda61d9af640c7:569246fd1e83ae0648e1a21ffb4fe811