id: prometheus-node_exporter-misconfiguration-metrics-bannercheck-direct

info:
  name: Prometheus Metrics - Detect
  author: dhiyaneshDK,philippedelteil,gordey
  severity: info
  description: Prometheus metrics page was detected.
  reference:
    - https://github.com/prometheus/prometheus
    - https://hackerone.com/reports/1026196
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    date: 23.01.2024
    expiration_date: 26.02.2024
    code_requirements:
    additional_files:
    nuclei_commandline:
    bdu-id:
    cok-id:
    template_type: bannercheck-direct
    max-request: 2
    verified: false
    shodan-query: |
      "Prometheus Node Exporter"
      http.title:"Node Exporter"
    netlas-query: http.title:"Node Exporter"
    rooster-query: |
      product.name:"node exporter"
    fofa-query: |
      "Prometheus Node Exporter" || title="Node Exporter"
    censys-query: |
      "Prometheus Node Exporter"
      services.http.response.html_title="Node Exporter"
    hunter-query: |
      web.title="Node Exporter"
      header="Prometheus Node Exporter"
    accuracy: 1
    damage: 0
    vendor: prometheus
    product: node_exporter
  tags: exposure,prometheus,hackerone,config,leak,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"
      - "{{BaseURL}}/api/metrics"
    headers:
        User-Agent: Mozilla/5.0 (compatible; CyberOKInspect/1.0; +https://www.cyberok.ru/policy.html)
    stop-at-first-match: true
    extractors:
      - type: regex
#        name: go_version
        group: 1
        regex:
          - 'go_info{version="go([\d\.]+)'

      - type: regex
        name: go_version
        internal: true
        group: 1
        regex:
          - 'go_info{version="go([\d\.]+)'


      - type: regex
#        name: build
        group: 1
        regex:
          - '_build_info{branch[^}]+version="([\d\.]+)'

      - type: regex
        name: build
        internal: true
        group: 1
        regex:
          - '_build_info{branch[^}]+version="([\d\.]+)'

      - type: regex
#        name: uname
        group: 1
        regex:
          - 'uname_info{[^}]+release=([^}]+)'

      - type: regex
        name: uname
        internal: true
        group: 1
        regex:
          - 'uname_info{[^}]+release=([^}]+)'

    matchers-condition: or
    matchers:
      - type: word
        name: prometheus-node_exporter-misconfiguration-metrics
        words:
          - '# HELP go_info Information about the Go environment.'
          - 'go_gc_duration_seconds'
        condition: and

#      - type: regex
#        name: go_version
#        part: go_version
#        regex:
#          - '[\d\.]*'
#
#      - type: regex
#        name: build
#        part: build
#        regex:
#          - '[\d\.]*'
#
#      - type: regex
#        name: uname
#        part: uname
#        regex:
#          - '[\d\.]*'

#https://endoflife.date/go
#Release        Released          Supported         Latest
#1.21         08 Aug 2023             Yes           1.21.5  05 Dec 2023
#1.20         01 Feb 2023             Yes           1.20.12 05 Dec 2023
#1.19         02 Aug 2022         Ended 06 Sep 2023 1.19.13 06 Sep 2023


      - type: dsl
        name: EOL
        dsl: 
          - compare_versions(go_version, '>0', '<1.20')


#https://github.com/advisories/GHSA-r969-8v3h-23v9
#https://www.opencve.io/cve?vendor=apache&product=nifi
#golang vuln - just for fun

      - type: dsl
        name: CVE-2023-24538
        condition: or
        dsl: 
          - compare_versions(go_version, '>0','<1.19.8')
          - compare_versions(go_version, '>=1.20.0','<1.20.3')

#https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md
#2.40.4 / 2022-11-29
#[SECURITY] Fix basic authentication bypass vulnerability (CVE-2022-46146). GHSA-4v48-4q5m-8vx4

#Prometheus Exporter Toolkit is a utility package to build exporters. Prior to versions 0.7.2 and 0.8.2, 
#if someone has access to a Prometheus web.yml file and users' bcrypted passwords, they can bypass security by poisoning the built-in authentication cache.
#Versions 0.7.2 and 0.8.2 contain a fix for the issue. There is no workaround, but attacker must have access to the hashed password to use this functionality.



      - type: dsl
        name: CVE-2022-46146
        condition: or
        dsl: 
          - compare_versions(build, '>0','<2.40.4')


#Other vulns
#2.13.0 / 2019-10-04
#[SECURITY/BUGFIX] UI: Fix a Stored DOM XSS vulnerability with query history CVE-2019-10215. #6098
#2.27.1 / 2021-05-18
#[BUGFIX] SECURITY: Fix arbitrary redirects under the /new endpoint (CVE-2021-29622)
#2.33.5 / 2022-03-08
#The binaries published with this release are built with Go1.17.8 to avoid CVE-2022-24921.