id: prometheus-node_exporter-misconfiguration-flags-safecheck

info:
  name: Prometheus flags API endpoint
  author: geeknik
  severity: info
  description: The flags endpoint provides a full path to the configuration file. If the file is stored in the home directory, it may leak a username.
  reference:
    - https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  metadata:
    date: 23.01.2024
    expiration_date: 26.02.2024
    code_requirements:
    additional_files:
    nuclei_commandline:
    bdu-id:
    cok-id:
    template_type: safecheck
    max-request: 1
    verified: false
    shodan-query: |
      "Prometheus Node Exporter"
      http.title:"Node Exporter"
    netlas-query: http.title:"Node Exporter"
    rooster-query: |
      product.name:"node exporter"
    fofa-query: |
      "Prometheus Node Exporter" || title="Node Exporter"
    censys-query: |
      "Prometheus Node Exporter"
      services.http.response.html_title="Node Exporter"
    hunter-query: |
      web.title="Node Exporter"
      header="Prometheus Node Exporter"
    accuracy: 1
    damage: 0.1
    vendor: prometheus
    product: node_exporter
  tags: prometheus,leak,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/status/flags"
    headers:
        User-Agent: Mozilla/5.0 (compatible; CyberOKInspect/1.0; +https://www.cyberok.ru/policy.html)
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"data":'
          - '"config.file":'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

    extractors:
      - type: regex
        name: web_admin_enabled
        regex:
          - '"web.enable-admin-api":"true"'

      - type: regex
        name: web_lifecycle_enabled
        regex:
          - '"web.enable-lifecycle":"true"'
          

