id: psalm-config

info:
  name: Psalm Configuration Exposure - Detect
  author: DhiyaneshDK
  severity: low
  description: |
    Psalm configuration page was detected.
  reference:
    - https://psalm.dev/docs/running_psalm/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"psalm.xml"
  tags: devops,exposure,php,psalm,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/psalm.xml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<psalm'
          - '<projectFiles'
          - 'xmlns:xsi'
        condition: and

      - type: word
        part: header
        words:
          - "application/xml"

      - type: status
        status:
          - 200

# digest: 490a0046304402200efe8e453db031850aa3a44184ce1654e4347857f62d57ad61d67526552bc13f02205bbc7ff4bf973827713ce3d043a5fc4db1fede68830b18bebf704b8cf830350d:922c64590222798bb761d5b6d8e72950
