id: raspberry-shake-config

info:
  name: Raspberry Shake Config Detection
  author: pussycat0x
  severity: medium
  description: |
    The Shake Board digitizer receives, processes, and interprets the sensor data in real-time, allowing for the Raspberry Pi computer to export the data for easy access. The data output can be displayed and analyzed using our own comprehensive set of web tools or any standard seismological software.
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Raspberry Shake Config"
  tags: misconfig,unauth,iot,raspberry

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Raspberry Shake Config"

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100d0a523b0791f5f26895ba6340309a02c875e8399b33f038d34c199b3a2704f2502205b6c7dabfd5d26347131b24ca22c16981a73c666a3bd596c345eb6a1f19f390e:922c64590222798bb761d5b6d8e72950
