id: redis-config

info:
  name: Redis Configuration File - Detect
  author: geeknik
  severity: medium
  description: Redis configuration file was detected.
  reference:
    - https://redis.io/docs/manual/config/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"redis.conf"
  tags: redis,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/redis.conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "bind"
          - "protected-mode"
          - "port "
        condition: and

      - type: word
        part: header
        words:
          - "application/octet-stream"

      - type: status
        status:
          - 200

# digest: 490a00463044022011e1c22bdba32f91460c631c4a3b89f47cdf3e9826fc3dd2c789c87dfd1725c90220296413dc2c242c894ad8ef2017d64bdce91a2b9fb8ee0fbde35f43a09f4c52cc:922c64590222798bb761d5b6d8e72950
