id: redmine-config

info:
  name: Redmine Configuration File - Detect
  author: DhiyaneshDK
  severity: high
  description: Redmine configuration file was detected.
  reference:
    - https://www.exploit-db.com/ghdb/5803
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" configuration.yml
  tags: exposure,redmine,devops,edb,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.yml"
      - "{{BaseURL}}/config/configuration.yml"
      - "{{BaseURL}}/redmine/config/configuration.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "user_name"
          - "password"
          - "Redmine"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a004730450221008e4e264c850d0c89b1bda1b5b1db20a9d4877b16158e21ae10c295885027973f022054a74aca2bcb5442e2cd68cb5dff91d42c6f04c58f55cbce4bcf77da485f202b:922c64590222798bb761d5b6d8e72950
