id: s3cmd-config

info:
  name: S3CMD Configuration - Detect
  author: Ice3man
  severity: info
  description: S3CMD configuration information was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: amazon,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/s3cmd.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[default]'
          - 'access_key'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a004730450221009bed25dd91910f1571b9dd4af585bb5e55373c26f36505ef71239ae8aa14e590022018602eb3b80609a301f01468c9566798a97cf917a011cf622a2c3394e707d28d:922c64590222798bb761d5b6d8e72950
