id: save-extractor-values-to-file

info:
  name: save extractor values to file
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - '[0-9]+'
        to: output.txt