id: security-misconfiguration
info:
  name: Security Misconfiguration
  author: Ali Baykara
  severity: high
  description: |
    Detects common security misconfigurations such as exposed .env files that contain sensitive information.
  tags: owasp, misconfiguration

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.env"
    matchers:
      - type: word
        words:
          - "DB_PASSWORD"
