id: swagger-page

info:
  name: Verificação de Swagger em URLs
  author: [erickfernandox]
  severity: medium
  description: |
      Este template verifica varios caminhos possiveis nas URLs para achar paginas de Swagger UI.
  tags: 
    - injection
    - swagger

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger/"    
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui/index.html"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/api/"
      - "{{BaseURL}}/api/docs"
      - "{{BaseURL}}/api-doc"
      - "{{BaseURL}}/api-docs"      
      - "{{BaseURL}}/docs/index.html"      
      - "{{BaseURL}}/docs/"            
      - "{{BaseURL}}/docs/swagger-ui.html"    
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/swagger/ui/index.html"      
      - "{{BaseURL}}/swagger/ui/index"      
      - "{{BaseURL}}/api/swagger/index.html"
      - "{{BaseURL}}/api/swagger/ui/index"      
      - "{{BaseURL}}/api/swagger-ui/index.html" 
      - "{{BaseURL}}/api/docs/index.html" 
      - "{{BaseURL}}/api/doc/index.html"           
      - "{{BaseURL}}/api/index.html"      
      - "{{BaseURL}}/api/v1/swagger/index.html"
      - "{{BaseURL}}/api/v1/swagger-ui/index.html" 
      - "{{BaseURL}}/api/v1/swagger/ui/index"       
      - "{{BaseURL}}/api/v1/docs/index.html"   
      - "{{BaseURL}}/api/v1/docs/swagger-ui/index.html"   
      - "{{BaseURL}}/api/v1/docs/swagger/index.html"   
      - "{{BaseURL}}/api/v2/swagger/index.html"
      - "{{BaseURL}}/api/v2/docs/swagger-ui/index.html"   
      - "{{BaseURL}}/api/v2/docs/swagger/index.html"   
      - "{{BaseURL}}/api/v2/swagger-ui/index.html" 
      - "{{BaseURL}}/api/v2/swagger/ui/index"       
      - "{{BaseURL}}/api/v2/docs/index.html"   
      - "{{BaseURL}}/api/v3/swagger/index.html"
      - "{{BaseURL}}/api/v3/swagger-ui/index.html" 
      - "{{BaseURL}}/api/v3/docs/swagger-ui/index.html"   
      - "{{BaseURL}}/api/v3/docs/swagger/index.html"   
      - "{{BaseURL}}/api/v3/swagger/ui/index"             
      - "{{BaseURL}}/api/v3/docs/index.html"   
      - "{{BaseURL}}/docs/swagger-ui/index.html"    
      - "{{BaseURL}}/v1/swagger/index.html"
      - "{{BaseURL}}/v1/api"      
      - "{{BaseURL}}/v1/swagger-ui/index.html" 
      - "{{BaseURL}}/v1/swagger/ui/index"       
      - "{{BaseURL}}/v1/docs/index.html"    
      - "{{BaseURL}}/v1/api-docs/index.html"          
      - "{{BaseURL}}/v2/swagger/index.html"
      - "{{BaseURL}}/v2/api"      
      - "{{BaseURL}}/v2/api-docs/index.html"     
      - "{{BaseURL}}/v2/swagger-ui/index.html" 
      - "{{BaseURL}}/v2/swagger/ui/index"       
      - "{{BaseURL}}/v2/docs/index.html"   
      - "{{BaseURL}}/v3/swagger/index.html"
      - "{{BaseURL}}/v3/api-docs/index.html"     
      - "{{BaseURL}}/v3/swagger-ui/index.html" 
      - "{{BaseURL}}/v3/api"      
      - "{{BaseURL}}/v3/swagger/ui/index"       
      - "{{BaseURL}}/v3/docs/index.html"   
      - "{{BaseURL}}/"
      - "{{BaseURL}}/doc/"    
      - "{{BaseURL}}/v0/"         
      - "{{BaseURL}}/v1/"          
      - "{{BaseURL}}/v2/"          
      - "{{BaseURL}}/v3/"       
      - "{{BaseURL}}/api/schema/swagger-ui/"
      
      
    matchers:
      - type: word
        words:
          - "Swagger UI"  
