id: symfony-security

info:
  name: Symfony security.yml File Disclosure
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" "security.yml"
  tags: symfony,devops,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/security.yml"
      - "{{BaseURL}}/config/security.yml"
      - "{{BaseURL}}/app/config/security.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'security:'
          - 'providers:'
        condition: and

      - type: status
        status:
          - 200

# digest: 490a0046304402206b983d3e4e1ef38d3b4cae7cb19f910b490bd9d810342b577fd73e30f95ce72802206402029e10542ce58e676260699f3ec277efb05242fa7682891cd42ab28e0d40:922c64590222798bb761d5b6d8e72950
