id: symfony-security-config

info:
  name: Symfony Security Configuration File - Detect
  author: dahse89
  severity: info
  description: Symfony security configuration file was detected.
  reference:
    - https://symfony2-document.readthedocs.io/en/latest/book/security.html
    - https://symfony.com/doc/current/reference/configuration/security.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure,symfony

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/packages/security.yaml"
      - "{{BaseURL}}/app/config/security.yml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "security:"
          - "firewalls:"
          - "access_control:"
        condition: and
        part: body

# digest: 4a0a0047304502210091071ec153f9dd960795f9420467a6ca26ebc243adf0eaed3d63fe7879501e7102207dd4dfd1d9e1b99d744838246934a0ed81b70d437dbf7b99ec434ec5640f590c:922c64590222798bb761d5b6d8e72950
