id: wordpress-config-file-exposure

info:
  name: WordPress Config File Exposure
  author: ss7py
  severity: high
  description: Detects exposed WordPress configuration and backup files that may contain sensitive information.

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-config.php-backup"
      - "{{BaseURL}}/wp-config.php.orig"
      - "{{BaseURL}}/.wp-config.php.swp"
      - "{{BaseURL}}/wp-config-sample.php"
      - "{{BaseURL}}/wp-config.inc"
      - "{{BaseURL}}/wp-config.old"
      - "{{BaseURL}}/wp-config.txt"
      - "{{BaseURL}}/wp-config.php.txt"
      - "{{BaseURL}}/wp-config.php.bak"
      - "{{BaseURL}}/wp-config.php.old"
      - "{{BaseURL}}/wp-config.php.dist"
      - "{{BaseURL}}/wp-config.php.inc"
      - "{{BaseURL}}/wp-config.php.swp"
      - "{{BaseURL}}/wp-config.php.html"
      - "{{BaseURL}}/wp-config-backup.txt"
      - "{{BaseURL}}/wp-config.php.save"
      - "{{BaseURL}}/wp-config.php~"
      - "{{BaseURL}}/wp-config.php.original"
      - "{{BaseURL}}/wp-config.php.bak"
      - "{{BaseURL}}/_wpeprivate/config.json"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DB_PASSWORD"
          - "DB_USER"
          - "DB_NAME"
        condition: or
      - type: status
        status:
          - 200
