id: wordpress-misconfig
info:
  name: Wordpress Misconfigurations
  author: glatisant
  severity: high
requests:
  - method: GET
    redirects: false
    path:
      - '{{BaseURL}}/_wpeprivate/config.json'
      - '{{BaseURL}}/wp-content/debug.log'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - wpengine_apikey