id: wpeprivate-config-disclosure

info:
  name: WPE Private Config Disclosure
  author: h0tak88r
  severity: high
  description: |
    This template checks for the presence of the `/_wpeprivate/config.json` file, which may contain sensitive information.

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_wpeprivate/config.json"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "wpengine_apikey"
          - "WPENGINE_ACCOUNT"
          - "KEY_SALT"
          - "db_host"
          - "db_password"
        condition: or
