id: bulletproof-security

info:
  name: >
    BulletProof Security <= .53.2 - Cross-Site Scripting
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/eab98c41-f0f2-4953-b9b3-c08e1e92c03a?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/bulletproof-security/"
    google-query: inurl:"/wp-content/plugins/bulletproof-security/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,bulletproof-security,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/bulletproof-security/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "bulletproof-security"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= .53.2')