id: configurable-tag-cloud-widget

info:
  name: >
    Configurable Tag Cloud <= 5.2 - Cross-Site Request Forgery via ctc_options_page()
  author: topscoder
  severity: medium
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/0775b36b-d543-41f9-a20d-f629b40c70d7?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/configurable-tag-cloud-widget/"
    google-query: inurl:"/wp-content/plugins/configurable-tag-cloud-widget/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,configurable-tag-cloud-widget,medium

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/configurable-tag-cloud-widget/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "configurable-tag-cloud-widget"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 5.2')