id: configure-conference-room

info:
  name: >
    WP Virtual Room Configurator <= 1.0.0 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/c5f24f89-3653-452d-bb1e-8bc113770624?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/configure-conference-room/"
    google-query: inurl:"/wp-content/plugins/configure-conference-room/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,configure-conference-room,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/configure-conference-room/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "configure-conference-room"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0.0')