id: debug-log-config-tool

info:
  name: >
    Debug Log – Manger Tool <= 1.4.5 - Unauthenticated Information Exposure via Logs
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/44c74d97-47e1-4af7-83d1-7c0e98fdc40c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/debug-log-config-tool/"
    google-query: inurl:"/wp-content/plugins/debug-log-config-tool/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,debug-log-config-tool,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/debug-log-config-tool/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "debug-log-config-tool"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.4.5')