id: finance-calculator-with-application-form

info:
  name: >
    Financial Calculator <= 2.2.1 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/c9314970-1030-4488-8147-05ba1453182c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/finance-calculator-with-application-form/"
    google-query: inurl:"/wp-content/plugins/finance-calculator-with-application-form/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,finance-calculator-with-application-form,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/finance-calculator-with-application-form/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "finance-calculator-with-application-form"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.2.1')