id: fluent-security

info:
  name: >
    FluentAuth <= 1.0.1 -  IP Spoofing to Protection Mechanism Bypass
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/5b4f563c-a17b-4d69-9e94-7287da976e85?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/fluent-security/"
    google-query: inurl:"/wp-content/plugins/fluent-security/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,fluent-security,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/fluent-security/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "fluent-security"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0.1')