id: gmaps-for-visual-composer-free

info:
  name: >
    GMAPS for WPBakery Page Builder Free <= 1.2 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/2c251bf5-f6c0-4d2e-a240-95b0f1fce3f5?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/gmaps-for-visual-composer-free/"
    google-query: inurl:"/wp-content/plugins/gmaps-for-visual-composer-free/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,gmaps-for-visual-composer-free,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/gmaps-for-visual-composer-free/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "gmaps-for-visual-composer-free"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2')