id: hybrid-composer

info:
  name: >
    Hybrid Composer <= 1.4.6 - Missing Authorization to Arbitrary Options Update
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/1bc19bfa-ce44-4654-b074-c8126b60a155?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/hybrid-composer/"
    google-query: inurl:"/wp-content/plugins/hybrid-composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,hybrid-composer,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/hybrid-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "hybrid-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.4.6')