id: image-hover-effects-visual-composer-extension

info:
  name: >
    Image Hover Effects For WPBakery Page Builder <= 4.0 - Authenticated (Contributor+) Stored Cross-Site Scripting via shortcode
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/92ffaa23-08f2-4aa4-84c3-a84c26ed8474?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/image-hover-effects-visual-composer-extension/"
    google-query: inurl:"/wp-content/plugins/image-hover-effects-visual-composer-extension/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,image-hover-effects-visual-composer-extension,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/image-hover-effects-visual-composer-extension/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "image-hover-effects-visual-composer-extension"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 4.0')