id: image-hover-effects-ultimate-visual-composer

info:
  name: >
    Flipbox – Awesomes Flip Boxes Image Overlay <= 2.6.0 - Authenticated (Admin+) Arbitrary Options Update
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/3a63dd48-d643-41d0-84c3-2f2dbbe577dd?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/image-hover-effects-ultimate-visual-composer/"
    google-query: inurl:"/wp-content/plugins/image-hover-effects-ultimate-visual-composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,image-hover-effects-ultimate-visual-composer,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/image-hover-effects-ultimate-visual-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "image-hover-effects-ultimate-visual-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.6.0')