id: product-websites-showcase

info:
  name: >
    Product Website Showcase <= 1.0 - Unauthenticated Arbitrary File Upload
  author: topscoder
  severity: critical
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/94d67030-30ea-4583-a716-79805a5619e8?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-websites-showcase/"
    google-query: inurl:"/wp-content/plugins/product-websites-showcase/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-websites-showcase,critical

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-websites-showcase/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-websites-showcase"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0')