id: product-preview-for-woocommerce

info:
  name: >
    BeRocket Plugins <= (Various Versions) - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/b8fc89c0-292d-47b4-90b3-79edf3a9e76d?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-preview-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-preview-for-woocommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-preview-for-woocommerce,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-preview-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-preview-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.5.7.6')