id: product-reviews-import-export-for-woocommerce

info:
  name: >
    Product Reviews Import Export for WooCommerce <= 1.4.8 - CSV Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/e6650eb7-143f-4c8f-b18f-056fc82972fc?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-reviews-import-export-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-reviews-import-export-for-woocommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-reviews-import-export-for-woocommerce,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-reviews-import-export-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-reviews-import-export-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.4.8')