id: product-filter-for-woocommerce-product

info:
  name: "Product Filter For WooCommerce Product <= 1.3.1 - Unauthenticated SQL Injection"
  author: topscoder
  severity: high
  description: "The Product Filter For WooCommerce Product plugin for WordPress is vulnerable to SQL Injection via the `datastring` paramater in versions up to and including 1.3.1. This makes it possible for unauthenticated attackers to append additional SQL queries into already existing queries that can be used to extract sensitive information from the database."
  reference:
    - https://plugins.trac.wordpress.org/browser/product-filter-for-woocommerce-product/trunk/includes/ajax.php#L317
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id:
  metadata:
    fofa-query: "wp-content/plugins/product-filter-for-woocommerce-product/"
    google-query: inurl:"/wp-content/plugins/product-filter-for-woocommerce-product/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-filter-for-woocommerce-product,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-filter-for-woocommerce-product/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-filter-for-woocommerce-product"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.3.0')