id: product-blocks-for-woocommerce

info:
  name: >
    Product Blocks for WooCommerce <= 1.9.1 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/edb62de4-2d98-46fa-9244-585a547c0d27?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-blocks-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-blocks-for-woocommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-blocks-for-woocommerce,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-blocks-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-blocks-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.9.1')