id: product-recommendation-quiz-for-ecommerce

info:
  name: >
    Product Recommendation Quiz for eCommerce <= 2.1.0 - Missing Authorization in prq_set_token
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/f10ae2b6-1580-418c-9cf7-e75ed71bb309?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-recommendation-quiz-for-ecommerce/"
    google-query: inurl:"/wp-content/plugins/product-recommendation-quiz-for-ecommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-recommendation-quiz-for-ecommerce,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-recommendation-quiz-for-ecommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-recommendation-quiz-for-ecommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.1.0')