id: product-catalog-8-plugin

info:
  name: >
    Product Catalog 8 <= 1.2.0 - SQL Injection
  author: topscoder
  severity: critical
  description: >
    The Product Catalog 8 plugin for WordPress is vulnerable to SQL Injection via the ‘selectedCategory’ parameter in versions up to, and including, 1.2.0 due to insufficient escaping on a user supplied parameter and lack of sufficient preparation on the existing SQL query. This makes it possible for attackers to append additional SQL queries into already existing queries that can be used to extract sensitive information from the database.
  reference:
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/cc01bb79-67cd-40d8-b0e0-1853df1aa3c4?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-catalog-8/"
    google-query: inurl:"/wp-content/plugins/product-catalog-8/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-catalog-8,critical

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-catalog-8/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-catalog-8"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2.0')