id: product-filter-for-woocommerce-product

info:
  name: >
    Product Filter For WooCommerce Product <= 1.3.1 - Unauthenticated SQL Injection
  author: topscoder
  severity: critical
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/d52d3291-838a-4b23-b969-8c6273faec1e?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-filter-for-woocommerce-product/"
    google-query: inurl:"/wp-content/plugins/product-filter-for-woocommerce-product/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-filter-for-woocommerce-product,critical

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-filter-for-woocommerce-product/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-filter-for-woocommerce-product"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.3.0')