id: products-stock-manager-with-excel

info:
  name: >
    PHPSpreadsheet Library < 2.3.0 - XXE Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/38f950b7-e3a0-4e05-a8b0-9cc6b6c66b0c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/products-stock-manager-with-excel/"
    google-query: inurl:"/wp-content/plugins/products-stock-manager-with-excel/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,products-stock-manager-with-excel,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/products-stock-manager-with-excel/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "products-stock-manager-with-excel"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.8')