id: service

info:
  name: >
    Service <= 1.0.4 - Authenticated (Subscriber+) SQL Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/245fade9-ecbb-4d41-ae2a-07331f6c25ba?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/service/"
    google-query: inurl:"/wp-content/plugins/service/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,service,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/service/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "service"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0.4')