id: sg-security

info:
  name: >
    SiteGround Security <= 1.2.5 - Authorization Weakness to Authentication Bypass
  author: topscoder
  severity: critical
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/8e3a5566-eee5-4f71-9c93-e59abf913d04?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/sg-security/"
    google-query: inurl:"/wp-content/plugins/sg-security/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,sg-security,critical

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/sg-security/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "sg-security"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2.5')