id: ultimate-carousel-for-visual-composer

info:
  name: >
    Ultimate Carousel For WPBakery Page Builder <= 2.6 - Authenticated (Contributor+) Stored Cross-Site Scripting via Shortcode
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/c97fc289-1ee3-4401-a57e-b4c8d998259e?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/ultimate-carousel-for-visual-composer/"
    google-query: inurl:"/wp-content/plugins/ultimate-carousel-for-visual-composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,ultimate-carousel-for-visual-composer,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/ultimate-carousel-for-visual-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "ultimate-carousel-for-visual-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.6')