id: wh-cache-and-security

info:
  name: >
    WH Cache & Security <= 1.1.2 - Reflected Cross-Site Scripting
  author: topscoder
  severity: medium
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/e7d0c727-be79-4344-87de-86cdf3615874?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/wh-cache-and-security/"
    google-query: inurl:"/wp-content/plugins/wh-cache-and-security/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,wh-cache-and-security,medium

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/wh-cache-and-security/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "wh-cache-and-security"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.1.2')