id: wordpress-malcare-security

info:
  name: MalCare WordPress Security Plugin – Malware Scanner, Cleaner, Security Firewall Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/malcare-security/
  metadata:
    plugin_namespace: malcare-security
    wpscan: https://wpscan.com/plugin/malcare-security
  tags: tech,wordpress,wp-plugin,top-200

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/malcare-security/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/malcare-security.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
# digest: 4b0a00483046022100e91d8bd266e47e65e7a7581b3c498a66689b95a060de255a58cdbfcba12fc230022100fb5461e9442bb2af308441e8caab062a39f3229d092665dbb6c83578733f6833:922c64590222798bb761d5b6d8e72950