id: Wordpress-Config-Disclosure
info:
  name: Wordpress Configuration Disclosure
  description: 'Attacker can view the config file which contains the username and password'
  author: Hacktify Cyber Security (@hacktifycs)
  severity: high
  tags: wordpress,wp-admin,sde
  reference: |
    - null

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/setup-config.php?step=1' #endpoint
    cookie-reuse: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: regex
        regex:
          - 'Username'
        part: body
