id: wordpress-better-wp-security

info:
  name: Solid Security – Password, Two Factor Authentication, and Brute Force Protection Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/better-wp-security/
  metadata:
    plugin_namespace: better-wp-security
    wpscan: https://wpscan.com/plugin/better-wp-security
  tags: tech,wordpress,wp-plugin,top-100,top-200

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/better-wp-security/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/better-wp-security.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
# digest: 4a0a00473045022100dafcd5c4d6d8ba0d696d40aa278d130b8614a54458e3295cbc0d6e9d074121c402200f07bd23581c510fafb3e7e38ae2a75411c3356d8a21cd31b6a17550f6d204cc:922c64590222798bb761d5b6d8e72950