id: wp-config-file-editor

info:
  name: >
    WP Config File Editor <= 1.7.1 - Authenticated (Admin+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/f2ce4a14-5c56-4ca0-9deb-80cd609b71e6?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/wp-config-file-editor/"
    google-query: inurl:"/wp-content/plugins/wp-config-file-editor/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,wp-config-file-editor,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/wp-config-file-editor/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "wp-config-file-editor"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.7.1')