id: wp-config.php-exposer 
info:
  name: "WordPress accessible wp-config"
  author: enterlectury
  severity: high
  description: The remote WordPress installation has the `wp-config` file remotely accessible and its content available for reading.
  tags: wordpress-misc,wordpress,backups,config,misconfig

http:
  - method: GET
    path:
      - '{{BaseURL}}/backup.wp-config.php'
      - '{{BaseURL}}/wp-config'
      - '{{BaseURL}}/wp-config.'
      - '{{BaseURL}}/wp-config~'
      - '{{BaseURL}}/wp-config.0'
      - '{{BaseURL}}/wp-config._1'
      - '{{BaseURL}}/wp-config.1'
      - '{{BaseURL}}/wp-config._2'
      - '{{BaseURL}}/wp-config.2'
      - '{{BaseURL}}/wp-config.3'
      - '{{BaseURL}}/wp-config.4'
      - '{{BaseURL}}/wp-config.5'
      - '{{BaseURL}}/wp-config.6'
      - '{{BaseURL}}/wp-config.7'
      - '{{BaseURL}}/wp-config.8'
      - '{{BaseURL}}/wp-config.9'
      - '{{BaseURL}}/wp-config.a'
      - '{{BaseURL}}/wp-config.aws'
      - '{{BaseURL}}/wp-config.azure'
      - '{{BaseURL}}/wp-config.b'
      - '{{BaseURL}}/wp-config.bac'
      - '{{BaseURL}}/wp-config.back'
      - '{{BaseURL}}/wp-config-backup'
      - '{{BaseURL}}/wp-config._backup'
      - '{{BaseURL}}/wp-config.backup'
      - '{{BaseURL}}/wp-config_backup'
      - '{{BaseURL}}/wp-config-backup1.txt'
      - '{{BaseURL}}/wp-config-backup.php'
      - '{{BaseURL}}/wp-config-backup.txt'
      - '{{BaseURL}}/wp-config.backup.txt'
      - '{{BaseURL}}/wp-config.bak'
      - '{{BaseURL}}/wp-config.bak1'
      - '{{BaseURL}}/wp-config.bk'
      - '{{BaseURL}}/wp-config.bkp'
      - '{{BaseURL}}/wp-config.c'
      - '{{BaseURL}}/wp-config.cache'
      - '{{BaseURL}}/wp-config.cfg'
      - '{{BaseURL}}/wp-config.com'
      - '{{BaseURL}}/wp-config.conf'
      - '{{BaseURL}}/wp-config-copy.php'
      - '{{BaseURL}}/wp-config-Copy.php'
      - '{{BaseURL}}/wp-config.cs'
      - '{{BaseURL}}/wp-config.csproj'
      - '{{BaseURL}}/wp-config.cust'
      - '{{BaseURL}}/wp-config.data'
      - '{{BaseURL}}/wp-config.dev'
      - '{{BaseURL}}/wp-config.dif'
      - '{{BaseURL}}/wp-config.disabled'
      - '{{BaseURL}}/wp-config.dist'
      - '{{BaseURL}}/wp-config.dump'
      - '{{BaseURL}}/wp-config.err'
      - '{{BaseURL}}/wp-config-good'
      - '{{BaseURL}}/wp-config.good'
      - '{{BaseURL}}/wp-config_good'
      - '{{BaseURL}}/wp-config.gz'
      - '{{BaseURL}}/wp-config.htm'
      - '{{BaseURL}}/wp-config.html'
      - '{{BaseURL}}/wp-config.in'
      - '{{BaseURL}}/wp-config.inc'
      - '{{BaseURL}}/wp-config.ini'
      - '{{BaseURL}}/wp-config.java'
      - '{{BaseURL}}/wp-config.local'
      - '{{BaseURL}}/wp-config.local.php'
      - '{{BaseURL}}/wp-config.log'
      - '{{BaseURL}}/wp-config.lst'
      - '{{BaseURL}}/wp-config.maj'
      - '{{BaseURL}}/wp-config.map'
      - '{{BaseURL}}/wp-config.md'
      - '{{BaseURL}}/wp-config.new'
      - '{{BaseURL}}/wp-config.old'
      - '{{BaseURL}}/wp-config.old.old'
      - '{{BaseURL}}/wp-config.org'
      - '{{BaseURL}}/wp-config.ORG'
      - '{{BaseURL}}/wp-config.orig'
      - '{{BaseURL}}/wp-config.original'
      - '{{BaseURL}}/wp-config.part'
      - '{{BaseURL}}/._wp-config.php'
      - '{{BaseURL}}/wp-config.php#'
      - '{{BaseURL}}/wp-config.php'
      - '{{BaseURL}}/wp-config.php-'
      - '{{BaseURL}}/wp-config.php.'
      - '{{BaseURL}}/wp-config.php...'
      - '{{BaseURL}}/wp-config.php....'
      - '{{BaseURL}}/wp-config.php='
      - '{{BaseURL}}/wp-config.php_'
      - '{{BaseURL}}/wp-config.php__'
      - '{{BaseURL}}/wp-config.php______'
      - '{{BaseURL}}/wp-config.php~'
      - '{{BaseURL}}/wp-config.php~~~'
      - '{{BaseURL}}/wp-config.PHP'
      - '{{BaseURL}}/wp-config.php.0'
      - '{{BaseURL}}/wp-config.php0'
      - '{{BaseURL}}/wp-config.php.1'
      - '{{BaseURL}}/wp-config.php_1'
      - '{{BaseURL}}/wp-config.php~1'
      - '{{BaseURL}}/wp-config.php1'
      - '{{BaseURL}}/wp-config.php.2'
      - '{{BaseURL}}/wp-config.php2'
      - '{{BaseURL}}/wp-config.php.3'
      - '{{BaseURL}}/wp-config.php3'
      - '{{BaseURL}}/wp-config.php.4'
      - '{{BaseURL}}/wp-config.php4'
      - '{{BaseURL}}/wp-config.php.5'
      - '{{BaseURL}}/wp-config.php5'
      - '{{BaseURL}}/wp-config.php.6'
      - '{{BaseURL}}/wp-config.php6'
      - '{{BaseURL}}/wp-config.php.7'
      - '{{BaseURL}}/wp-config.php.8'
      - '{{BaseURL}}/wp-config.php.9'
      - '{{BaseURL}}/wp-config.php.a'
      - '{{BaseURL}}/wp-config.phpa'
      - '{{BaseURL}}/wp-config.php.aws'
      - '{{BaseURL}}/wp-config.php.azure'
      - '{{BaseURL}}/wp-config.php.b'
      - '{{BaseURL}}/wp-config.phpb'
      - '{{BaseURL}}/wp-config.php.bac'
      - '{{BaseURL}}/wp-config.php-backup'
      - '{{BaseURL}}/wp-config.php.backup'
      - '{{BaseURL}}/wp-config.php_backup'
      - '{{BaseURL}}/wp-config.php.backup.txt'
      - '{{BaseURL}}/wp-config.php-bak'
      - '{{BaseURL}}/wp-config.php.bak'
      - '{{BaseURL}}/wp-config.php_bak'
      - '{{BaseURL}}/wp-config.phpbak'
      - '{{BaseURL}}/wp-config.php.bak1'
      - '{{BaseURL}}/wp-config.php.bk'
      - '{{BaseURL}}/wp-config.php_bk'
      - '{{BaseURL}}/wp-config.php~bk'
      - '{{BaseURL}}/wp-config.php.bkp'
      - '{{BaseURL}}/wp-config.php.c'
      - '{{BaseURL}}/wp-config.phpc'
      - '{{BaseURL}}/wp-config.php.cache'
      - '{{BaseURL}}/wp-config.php.cfg'
      - '{{BaseURL}}/wp-config.php.com'
      - '{{BaseURL}}/wp-config.php.conf'
      - '{{BaseURL}}/wp-config.php.cs'
      - '{{BaseURL}}/wp-config.php.csproj'
      - '{{BaseURL}}/wp-config.php.cust'
      - '{{BaseURL}}/wp-config.phpd'
      - '{{BaseURL}}/wp-config.php.data'
      - '{{BaseURL}}/wp-config.php.dev'
      - '{{BaseURL}}/wp-config.php.dif'
      - '{{BaseURL}}/wp-config.php.disabled'
      - '{{BaseURL}}/wp-config.php.dist'
      - '{{BaseURL}}/wp-config.php.dump'
      - '{{BaseURL}}/wp-config.php.err'
      - '{{BaseURL}}/wp-config.php.gz'
      - '{{BaseURL}}/wp-config.php.html'
      - '{{BaseURL}}/wp-config.php.in'
      - '{{BaseURL}}/wp-config.php.inc'
      - '{{BaseURL}}/wp-config.php.ini'
      - '{{BaseURL}}/wp-config.php.java'
      - '{{BaseURL}}/wp-config.php.local'
      - '{{BaseURL}}/wp-config.php.log'
      - '{{BaseURL}}/wp-config.php.lst'
      - '{{BaseURL}}/wp-config.php.maj'
      - '{{BaseURL}}/wp-config.php.map'
      - '{{BaseURL}}/wp-config.php.md'
      - '{{BaseURL}}/wp-config.php-n'
      - '{{BaseURL}}/wp-config.phpn'
      - '{{BaseURL}}/wp-config.php.new'
      - '{{BaseURL}}/wp-config.php_new'
      - '{{BaseURL}}/wp-config.phpnew'
      - '{{BaseURL}}/wp-config.php-o'
      - '{{BaseURL}}/wp-config.php-old'
      - '{{BaseURL}}/wp-config.php.old'
      - '{{BaseURL}}/wp-config.php_old'
      - '{{BaseURL}}/wp-config.phpold'
      - '{{BaseURL}}/wp-config.php_old2003'
      - '{{BaseURL}}/wp-config.php_old2004'
      - '{{BaseURL}}/wp-config.php_old2005'
      - '{{BaseURL}}/wp-config.php_old2006'
      - '{{BaseURL}}/wp-config.php_old2007'
      - '{{BaseURL}}/wp-config.php_old2008'
      - '{{BaseURL}}/wp-config.php_old2009'
      - '{{BaseURL}}/wp-config.php_old2010'
      - '{{BaseURL}}/wp-config.php_old2011'
      - '{{BaseURL}}/wp-config.php_old2012'
      - '{{BaseURL}}/wp-config.php_old2013'
      - '{{BaseURL}}/wp-config.php_old2014'
      - '{{BaseURL}}/wp-config.php_old2015'
      - '{{BaseURL}}/wp-config.php_old2016'
      - '{{BaseURL}}/wp-config.php_old2017'
      - '{{BaseURL}}/wp-config.php_old2018'
      - '{{BaseURL}}/wp-config.php_old2019'
      - '{{BaseURL}}/wp-config.php_old2020'
      - '{{BaseURL}}/wp-config.php_old2021'
      - '{{BaseURL}}/wp-config.php_old2022'
      - '{{BaseURL}}/wp-config.php_old2023'
      - '{{BaseURL}}/wp-config.php_old2024'
      - '{{BaseURL}}/wp-config.php__olds'
      - '{{BaseURL}}/wp-config.php.org'
      - '{{BaseURL}}/wp-config.php.orig'
      - '{{BaseURL}}/wp-config.php_orig'
      - '{{BaseURL}}/wp-config.php-original'
      - '{{BaseURL}}/wp-config.php.original'
      - '{{BaseURL}}/wp-config.php_original'
      - '{{BaseURL}}/wp-config.phporiginal'
      - '{{BaseURL}}/wp-config.php.part'
      - '{{BaseURL}}/wp-config.php.php-bak'
      - '{{BaseURL}}/wp-config.php.prod'
      - '{{BaseURL}}/wp-config.php.production'
      - '{{BaseURL}}/wp-config.php.rej'
      - '{{BaseURL}}/wp-config.phps'
      - '{{BaseURL}}/wp-config.php.sample'
      - '{{BaseURL}}/wp-config.php.sass-cache'
      - '{{BaseURL}}/wp-config.php.sav'
      - '{{BaseURL}}/wp-config.php-save'
      - '{{BaseURL}}/wp-config.php.save'
      - '{{BaseURL}}/wp-config.php.save.1'
      - '{{BaseURL}}/wp-config.php.save.2'
      - '{{BaseURL}}/wp-config.php.save.3'
      - '{{BaseURL}}/wp-config.php.stage'
      - '{{BaseURL}}/wp-config.php.staging'
      - '{{BaseURL}}/wp-config.php.sublime-project'
      - '{{BaseURL}}/wp-config.php.sublime-workspace'
      - '{{BaseURL}}/.wp-config.php.swm'
      - '{{BaseURL}}/.wp-config.php.swn'
      - '{{BaseURL}}/wp-config.php.swn'
      - '{{BaseURL}}/.wp-config.php.swo'
      - '{{BaseURL}}/wp-config.php.swo'
      - '{{BaseURL}}/.wp-config.php.swp'
      - '{{BaseURL}}/wp-config.php.swp'
      - '{{BaseURL}}/wp-config.php.tar'
      - '{{BaseURL}}/wp-config.php.tar.gz'
      - '{{BaseURL}}/wp-config.php.temp'
      - '{{BaseURL}}/wp-config.php.templ'
      - '{{BaseURL}}/wp-config.php.tmp'
      - '{{BaseURL}}/wp-config.phptmp'
      - '{{BaseURL}}/wp-config.php.txt'
      - '{{BaseURL}}/wp-config.php.uk'
      - '{{BaseURL}}/wp-config.php.un~'
      - '{{BaseURL}}/wp-config.php.us'
      - '{{BaseURL}}/wp-config.php.vb'
      - '{{BaseURL}}/wp-config.php.vbproj'
      - '{{BaseURL}}/wp-config.php.vi'
      - '{{BaseURL}}/wp-config.php-work'
      - '{{BaseURL}}/wp-config.php.zip'
      - '{{BaseURL}}/wp-config.prod'
      - '{{BaseURL}}/wp-config.prod.php.txt'
      - '{{BaseURL}}/wp-config.prod.txt'
      - '{{BaseURL}}/wp-config.production'
      - '{{BaseURL}}/wp-config.rar'
      - '{{BaseURL}}/wp-config.rej'
      - '{{BaseURL}}/wp-config.sample'
      - '{{BaseURL}}/wp-config-sample.bak'
      - '{{BaseURL}}/wp-config-sample.php'
      - '{{BaseURL}}/wp-config-sample.php~'
      - '{{BaseURL}}/wp-config-sample.php.bak'
      - '{{BaseURL}}/wp-config.sass-cache'
      - '{{BaseURL}}/wp-config.sav'
      - '{{BaseURL}}/wp-config.save'
      - '{{BaseURL}}/wp-config.save.1'
      - '{{BaseURL}}/wp-config.save.2'
      - '{{BaseURL}}/wp-config.save.3'
      - '{{BaseURL}}/wp-config.stage'
      - '{{BaseURL}}/wp-config.staging'
      - '{{BaseURL}}/wp-config.sublime-project'
      - '{{BaseURL}}/wp-config.sublime-workspace'
      - '{{BaseURL}}/.wp-config.swm'
      - '{{BaseURL}}/.wp-config.swn'
      - '{{BaseURL}}/wp-config.swn'
      - '{{BaseURL}}/.wp-config.swo'
      - '{{BaseURL}}/wp-config.swo'
      - '{{BaseURL}}/.wp-config.swp'
      - '{{BaseURL}}/wp-config.swp'
      - '{{BaseURL}}/wp-config.tar'
      - '{{BaseURL}}/wp-config.tar.gz'
      - '{{BaseURL}}/wp-config.temp'
      - '{{BaseURL}}/wp-config.templ'
      - '{{BaseURL}}/wp-config.tmp'
      - '{{BaseURL}}/wp-config,txt'
      - '{{BaseURL}}/wp-config.txt'
      - '{{BaseURL}}/wp-config.uk'
      - '{{BaseURL}}/wp-config.un~'
      - '{{BaseURL}}/wp-config.us'
      - '{{BaseURL}}/wp-config.vb'
      - '{{BaseURL}}/wp-config.vbproj'
      - '{{BaseURL}}/wp-config.vi'
      - '{{BaseURL}}/wp-config.wp-config.php.swo'
      - '{{BaseURL}}/wp-config.wp-config.php.swp'
      - '{{BaseURL}}/wp-config.zip'
      - '{{BaseURL}}/_wpeprivate/config.json'
      
matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - DB_NAME
          - WPENGINE_ACCOUNT
      - type: status
        status:
          - 200
