id: wp-config-setup

info:
  name: WordPress Setup Configuration
  author: princechaddha
  severity: high
  reference:
    - https://smaranchand.com.np/2020/04/misconfigured-wordpress-takeover-to-remote-code-execution/
  metadata:
    max-request: 1
  tags: wordpress,setup

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/setup-config.php?step=1"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Below you should enter your database connection details."

      - type: status
        status:
          - 200

# digest: 4b0a00483046022100e979a8be5bb6a555e42d5d6d7e12f302f4a0a0f20ac4bdf0da56786206432cbb022100b26fd2d09915a684fcb09f935ad6af161008ff39c7f3d094484a20a7c1008ba3:922c64590222798bb761d5b6d8e72950
