id: wp-superstorefinder-misconfig

info:
  name: Superstorefinder WP-plugin - Security Misconfigurations
  author: r3Y3r53
  severity: medium
  description: |
    Security misconfiguration is a common security issue that occurs when a system, application, or network is not properly configured to protect against threats and vulnerabilities.
  reference:
    - https://cxsecurity.com/issue/WLB-2021010145
    - https://www.exploitalert.com/view-details.html?id=36983
  metadata:
    verified: true
    max-request: 1
    publicwww-query: /wp-content/plugins/superstorefinder-wp/
    google-query: inurl:"wp-content/plugins/superstorefinder-wp/ssf-wp-admin/pages/exportAjax.php"
  tags: wordpress,wp-plugin,superstorefinder-wp,wp,misconfig

http:
  - raw:
      - |
        GET /wp-content/plugins/superstorefinder-wp/ssf-wp-admin/pages/exportAjax.php HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "Name") && contains(body, "CategoriesTags") && contains(body, "email")'
          - 'contains(content_type, "text/html")'
        condition: and

# digest: 490a0046304402205624314a7fa843184b0006a4166011527395e568b8ad05b057c6736e989da9ba02200811b24c1e44539543fbb7c61236aa51bea06d2e84315390ed2377fb5f156f91:922c64590222798bb761d5b6d8e72950
